# Generated by Django 5.0.2 on 2024-03-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=150, verbose_name='Titulo Plan')),
                ('img', models.ImageField(upload_to='img/planes', verbose_name='Imagen del plan')),
                ('det', models.TextField(max_length=500, verbose_name='Detalle del Plan')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['-created'],
            },
        ),
    ]
