# Generated by Django 5.0.2 on 2024-03-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_entregas_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='img',
            field=models.ImageField(default=1, upload_to='personal/', verbose_name='Imagen Entregas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonios',
            name='img',
            field=models.ImageField(default=1, upload_to='testimonios/', verbose_name='Imagen Entregas'),
            preserve_default=False,
        ),
    ]
