# Generated by Django 5.0.2 on 2024-03-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonios',
            name='tes',
            field=models.TextField(verbose_name='Testimonio'),
        ),
    ]
